### ISSUE TITLE
Gestion du pg_service.conf

### ISSUE THREAD

**Issue by afourneyron** [lpoaura/lpo_qgis_profiles#7]
### Feature description

Question posée pour savoir comment gérer le fichier pg_service avec deux profile et deux connexions différentes, prendre en compte les cas où il n'y a qu'un profile sur le post, mais aussi le cas où les deux profile sont déployés... Possibilité de merge en un seul fichier ? passage par GPO plus pratique ? 

#https://github.com/Guts/qgis-deployment-cli/discussions/482

**Comment by lpojgc** [comment]
principe réglé mais ne fonctionne pas... (cf autre ticket pen,se bete pour mardi)
